In [1]:
# Import the necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as seaborn
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [2]:
# Load the datasets
data = pd.read_csv('Churn_Modelling.csv')
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [4]:
data.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [5]:
data.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [6]:
# Preprocess the datasets
# Drop the unnecessary features
data = data.drop(['RowNumber','CustomerId', 'Surname'], axis=1)
data.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      10000 non-null  int64  
 1   Geography        10000 non-null  object 
 2   Gender           10000 non-null  object 
 3   Age              10000 non-null  int64  
 4   Tenure           10000 non-null  int64  
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64  
 7   HasCrCard        10000 non-null  int64  
 8   IsActiveMember   10000 non-null  int64  
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64  
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB


In [8]:
## Encode the categorical features
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France       0   42       2       0.00              1   
1             608     Spain       0   41       1   83807.86              1   
2             502    France       0   42       8  159660.80              3   
3             699    France       0   39       1       0.00              2   
4             850     Spain       0   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France       1   39       5       0.00              2   
9996          516    France       1   35      10   57369.61              1   
9997          709    France       0   36       7       0.00              1   
9998          772   Germany       1   42       3   75075.31              2   
9999          792    France       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [9]:
data['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [10]:
### One hot encoder

from sklearn.preprocessing import OneHotEncoder

onehot_encode_geo = OneHotEncoder(sparse_output=False)
geo_encoder = onehot_encode_geo.fit_transform(data[['Geography']])
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [11]:
onehot_encode_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [12]:
geo_encoded_df = pd.DataFrame(geo_encoder, columns=onehot_encode_geo.get_feature_names_out(['Geography']))
geo_encoded_df

Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [13]:
### Combine one hot encoder columns with the original data
data = pd.concat([data.drop('Geography', axis=1),geo_encoded_df], axis=1)
data.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0               1        101348.88       1               1.0   
1               1        112542.58       0               0.0   
2               0        113931.57       1               1.0   
3               0         93826.63       0               1.0   
4               1         79084.10       0               0.0   

   Geography_Germany  Geography_Spain  
0                0.0              0.0  
1                0.0              1.0  
2                0.0              0.0  
3                0.0              0.0  
4                0.0              1.0

In [14]:
### Save the encoders and scalar
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encode_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encode_geo, file)

In [15]:
data.isnull().sum()

CreditScore          0
Gender               0
Age                  0
Tenure               0
Balance              0
NumOfProducts        0
HasCrCard            0
IsActiveMember       0
EstimatedSalary      0
Exited               0
Geography_France     0
Geography_Germany    0
Geography_Spain      0
dtype: int64

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   CreditScore        10000 non-null  int64  
 1   Gender             10000 non-null  int64  
 2   Age                10000 non-null  int64  
 3   Tenure             10000 non-null  int64  
 4   Balance            10000 non-null  float64
 5   NumOfProducts      10000 non-null  int64  
 6   HasCrCard          10000 non-null  int64  
 7   IsActiveMember     10000 non-null  int64  
 8   EstimatedSalary    10000 non-null  float64
 9   Exited             10000 non-null  int64  
 10  Geography_France   10000 non-null  float64
 11  Geography_Germany  10000 non-null  float64
 12  Geography_Spain    10000 non-null  float64
dtypes: float64(5), int64(8)
memory usage: 1015.8 KB


In [17]:
### Divide the datast into dependent and independent features

X = data.drop('Exited', axis=1)
y = data['Exited']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=12)

In [18]:
### Scaling the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [19]:
X_train

array([[ 0.72682704,  0.91025899,  0.19876101, ...,  0.99128795,
        -0.57792762, -0.57003687],
       [ 0.932858  , -1.09858844, -0.2771138 , ...,  0.99128795,
        -0.57792762, -0.57003687],
       [-0.72569129,  0.91025899,  1.05533567, ...,  0.99128795,
        -0.57792762, -0.57003687],
       ...,
       [-1.27167336, -1.09858844, -0.65781365, ...,  0.99128795,
        -0.57792762, -0.57003687],
       [-1.302578  ,  0.91025899,  0.4842859 , ...,  0.99128795,
        -0.57792762, -0.57003687],
       [ 0.80923942,  0.91025899, -1.22886342, ..., -1.00878862,
         1.73032049, -0.57003687]])

In [20]:
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

# ANN Implemntation

In [21]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input, Dropout
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [22]:
## Build the ANN model
model=Sequential([
    Dense(128,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(64,activation='relu'),
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid') 
])

/Users/gopalakrishnanm/Documents/Programming/Machine Learning Projects/Krish Naik Udemy/ClassificationANN/venv/lib/python3.11/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [23]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │         1,664 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 12,033 (47.00 KB)

 Trainable params: 12,033 (47.00 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
import tensorflow
opt = tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss = tensorflow.keras.losses.BinaryCrossentropy()
loss

In [25]:
## Compile the model

model.compile(optimizer=opt,
              loss=loss,
              metrics=['accuracy'])

In [26]:
## Setup the tensorBoard
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d - %H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [27]:
## Set up Early Stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)


In [28]:
X_train.shape

(8000, 12)

In [29]:
X_train

array([[ 0.72682704,  0.91025899,  0.19876101, ...,  0.99128795,
        -0.57792762, -0.57003687],
       [ 0.932858  , -1.09858844, -0.2771138 , ...,  0.99128795,
        -0.57792762, -0.57003687],
       [-0.72569129,  0.91025899,  1.05533567, ...,  0.99128795,
        -0.57792762, -0.57003687],
       ...,
       [-1.27167336, -1.09858844, -0.65781365, ...,  0.99128795,
        -0.57792762, -0.57003687],
       [-1.302578  ,  0.91025899,  0.4842859 , ...,  0.99128795,
        -0.57792762, -0.57003687],
       [ 0.80923942,  0.91025899, -1.22886342, ..., -1.00878862,
         1.73032049, -0.57003687]])

In [30]:
X_test.shape

(2000, 12)

In [31]:
X_test

array([[-0.025186  ,  0.91025899, -0.56263868, ..., -1.00878862,
         1.73032049, -0.57003687],
       [ 0.41778058,  0.91025899, -0.18193884, ...,  0.99128795,
        -0.57792762, -0.57003687],
       [ 2.05572678, -1.09858844,  0.29393597, ...,  0.99128795,
        -0.57792762, -0.57003687],
       ...,
       [ 0.57230381, -1.09858844, -0.18193884, ..., -1.00878862,
        -0.57792762,  1.75427249],
       [-0.33423245, -1.09858844,  0.10358605, ..., -1.00878862,
         1.73032049, -0.57003687],
       [-1.38499039, -1.09858844, -0.56263868, ..., -1.00878862,
         1.73032049, -0.57003687]])

In [32]:
y_test.shape

(2000,)

In [33]:
### Train the model
history = model.fit(X_train, y_train, validation_data=(X_test, y_test), callbacks=[tensorflow_callback, early_stopping_callback],epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8127 - loss: 0.4336 - val_accuracy: 0.8510 - val_loss: 0.3686
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 687us/step - accuracy: 0.8533 - loss: 0.3569 - val_accuracy: 0.8445 - val_loss: 0.3656
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 696us/step - accuracy: 0.8497 - loss: 0.3550 - val_accuracy: 0.8610 - val_loss: 0.3529
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 690us/step - accuracy: 0.8639 - loss: 0.3315 - val_accuracy: 0.8625 - val_loss: 0.3609
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 683us/step - accuracy: 0.8643 - loss: 0.3317 - val_accuracy: 0.8610 - val_loss: 0.3638
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 668us/step - accuracy: 0.8533 - loss: 0.3470 - val_accuracy: 0.8565 - val_loss: 0.3514
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - accuracy: 0.8651 - loss: 0.3314 - val_accuracy: 0.8585 - val_loss: 0.3503
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 673us/step - accuracy: 0.8596 - loss: 0.3

In [34]:
model.save('model.h5')

In [35]:
## Load Tensorboard Extension
%load_ext tensorboard

In [36]:

%tensorboard --logdir logs/fit

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
Traceback (most recent call last):
  File "/Users/gopalakrishnanm/Documents/Programming/Machine Learning Projects/Krish Naik Udemy/ClassificationANN/venv/bin/tensorboard", line 7, in <module>
    from tensorboard.main import run_main
  File "/Users/gopalakrishnanm/Documents/Programming/Machine Learning Projects/Krish Naik Udemy/ClassificationANN/venv/lib/python3.11/site-packages/tensorboard/main.py", line 27, in <module>
    from tensorboard import default
  File "/Users/gopalakrishnanm/Documents/Programming/Machine Learning Projects/Krish Naik Udemy/ClassificationANN/venv/lib/python3.11/site-packages/tensorboard/default.py", line 33, in <module>
    from tensorboard.plugins.core import core_plugin
  File "/Users/gopalakrishnanm/Documents/Programming/Machine Learning Projects/Krish Naik Udemy/ClassificationANN/venv/lib/python3.11/site-packages/tensorboard/plugins/core/core_plugin.py", line 32, in <module>
    from

In [37]:
### load the pickle file


In [38]:
print(tf.__version__)
print(np.__version__)

2.17.0
1.26.4
